project:
  type: website

website:
  title: "Tech'n'Take"
  site-url: https://tech.ycwu.space
  description: "This is Jerry Wu's Tech'n'take."
  navbar:
    right:
      - icon: rss
        href: index.xml
      - icon: github
        href: https://gh.ycwu.space/
      - icon: linkedin
        href: https://cv.ycwu.space/

format:
  html:
    theme:
      light: spacelab
      dark: darkly
    toc: false
    toc-location: none
    css: styles.css
# execute:
#   freeze: auto