on:
    workflow_dispatch:
    push:
      branches: master
  
name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: 3.12
    - run: uv pip install --python=3.12 pip
    - run: uv venv venv
    - run: source venv/bin/activate
    - run: uv pip install -r requirements.txt

    - name: Render and Publish
      uses: quarto-dev/quarto-actions/publish@v2
      with:
        target: gh-pages
        env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}